export const ATTACK_PATTERNS: Record<string, RegExp[]> = {
  SQL_INJECTION: [
    /(\b(SELECT|INSERT|UPDATE|DELETE|DROP|UNION|ALTER|CREATE|EXEC|EXECUTE)\b)/gi,
    /(\b(OR|AND)\b\s+\d+\s*=\s*\d+)/gi,
    /('|\")(\s*OR\s*('|")|;\s*--|;\s*DROP|;\s*SELECT)/gi,
    /(\bWAITFOR\s+DELAY\b)/gi,
    /(\bBENCHMARK\s*\()/gi,
    /(\bSLEEP\s*\()/gi,
    /(--\s*$|\/\*.*?\*\/)/gm,
    /(\bINTO\s+(OUT|DUMP)FILE\b)/gi,
    /(\bLOAD_FILE\s*\()/gi,
    /(\binformation_schema\b)/gi,
  ],
  XSS: [
    /<\s*script[^>]*>/gi,
    /javascript\s*:/gi,
    /on\w+\s*=\s*['"]?/gi,
    /<\s*img[^>]+onerror\b/gi,
    /<\s*svg[^>]*>/gi,
    /<\s*iframe[^>]*>/gi,
    /<\s*object[^>]*>/gi,
    /<\s*embed[^>]*>/gi,
    /<\s*link[^>]*>/gi,
    /<\s*style[^>]*>/gi,
    /document\.\w+/gi,
    /window\.\w+/gi,
    /eval\s*\(/gi,
    /alert\s*\(/gi,
    /expression\s*\(/gi,
  ],
  COMMAND_INJECTION: [
    /(\b;|&&|\|\||\||`)/g,
    /\$\(/g,
    /(\bcat\b|\bls\b|\bdir\b|\bwhoami\b|\bifconfig\b|\bping\b|\bnslookup\b|\bnet\b)/gi,
    /(\/etc\/passwd|\/etc\/shadow|\/etc\/hosts)/gi,
    /(\/bin\/sh|\/bin\/bash|\/bin\/cmd|\/bin\/powershell)/gi,
    /(\bEXEC\b|\bEXECUTE\b)/gi,
    /\|(\s*curl|\s*wget|\s*nc|\s*netcat|\s*bash|\s*sh)/gi,
  ],
  PATH_TRAVERSAL: [
    /\.\.\//g,
    /\.\.[\\/]/g,
    /\.\.%2[fF]/g,
    /\.\.%5[cC]/g,
    /%2e%2e/gi,
    /%252e%252e/gi,
    /%2[fF]/g,
    /%5[cC]/g,
    /\x00/g,
  ],
  CRLF: [
    /\r\n/g,
    /\n\r/g,
    /%0[dD]%0[aA]/g,
    /%0[aA]%0[dD]/g,
    /%0[dD]/g,
    /%0[aA]/g,
    /\x0d\x0a/g,
    /\x0a\x0d/g,
  ],
  SSTI: [
    /\{\{.*?\}\}/g,
    /\{\%.*?\%\}/g,
    /\$\{.*?\}/g,
    /<%=.*?%>/g,
    /<\?.*?\?>/g,
    /\{\{.*?\}\}/g,
    /\#\(.*?\)/g,
  ],
  OPEN_REDIRECT: [
    /https?:\/\/(?!localhost|127\.0\.0\.1)/gi,
    /\/\/[^\/]+/gi,
    /\/(\/\/|\\\/)/gi,
    /%2[fF]%2[fF]/gi,
    /%252[fF]%252[fF]/gi,
  ],
  LDAP_INJECTION: [
    /(\(|\))/g,
    /(\*|\))/g,
    /(\&|\|)/g,
    /\\\\x/g,
    /[\x00]/g,
  ],
  XPATH_INJECTION: [
    /(\|\|)/g,
    /(\&&)/g,
    /(=\s*'|=\s*")/g,
    /(=\s*"|=\s*')/g,
    /(\|)/g,
    /(&&)/g,
  ],
};